name: ci

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm i -g factoriomod-debug
    - run: fmtk package
    - uses: actions/upload-artifact@v4
      with:
        path: 'loaded-turrets_*.zip'
    # - if: startsWith(github.ref, 'refs/tags/v')
    #   run: fmtk publish
    #   with:
    #     env:
    #       FACTORIO_UPLOAD_API_KEY: ${{ secrets.FACTORIO_UPLOAD_API_KEY }}
